<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class AuthenticationControllerTest extends TestCase
{
    use WithFaker, RefreshDatabase;

    private User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
    }

    public function testUserCanRegister()
    {
        $newUserData = [
            'email' => $this->faker->email,
            'name' => 'new user',
            'password' => '12345678',
            'password_confirmation' => '12345678',
        ];
        $response = $this->post(route('user_register'), $newUserData);
        $response->assertStatus(201);
    }

    public function testUserCanLoggedIn()
    {
        $userCredential = [
            'email' => $this->user->email,
            'password' => 'password'
        ];
        $response = $this->post(route('user_login'), $userCredential);
        $response->assertStatus(201);
    }

    public function testUserCanLoggedOut()
    {
        Sanctum::actingAs($this->user);
        $response = $this->post(route('user_logout'));
        $response->assertStatus(204);
    }
}
